import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import { Suspense } from "react";
import { createClient } from "@/utils/supabase/server";
export const metadata: Metadata = {
  title: {
    absolute: "IntelliNex"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: services, error } = await supabase
    .from('fa_services')
    .select("*")
    .eq('status', true);

  if (error) {
    console.log("❌ Supabase Error: ", error.message)
    return null;
  }

  // console.log("✅ Service Fetched: \n", services);

  return (
    <>
      <Header />
      <Suspense>
        {children}
      </Suspense>
      <Footer data={services} />
    </>
  );
}
