import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import React from "react";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--poppins',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: {
    default: "Intellinex",
    template: "%s - Intellinex"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${poppins.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {modal}
          <Toaster visibleToasts={3} toastOptions={{
            style: {
              borderRadius: 99,
              height: 44,
              display: 'flex',
              alignItems: "center",
              justifyContent: "center",
              width: "auto",
              justifySelf: "center",
            }
          }} richColors={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}
